#ifndef OUTPUT_PIN_1
#define OUTPUT_PIN_1 PB0
#endif
#ifndef OUTPUT_PIN_1_REGISTER
#define OUTPUT_PIN_1_REGISTER DDRB
#endif
#ifndef OUTPUT_PIN_2
#define OUTPUT_PIN_2 PB1
#endif
#ifndef OUTPUT_PIN_2_REGISTER
#define OUTPUT_PIN_2_REGISTER DDRB
#endif
#ifndef SELECTED_OUTPUT_PIN
#define SELECTED_OUTPUT_PIN OUTPUT_PIN_1
#endif
#ifndef SELECTED_OUTPUT_PIN_REGISTER
#define SELECTED_OUTPUT_PIN_REGISTER OUTPUT_PIN_1_REGISTER
#endif

